print("Hello World!")
print("Welcome to Python")
print("ujwala")
print("I am Learning Python")
print("Python Programming")
print("Good Morning")
print("welcome Students")
print("Python is easy")
print("My First Program")
print("Hello from Python")
